version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 5
          group: 5 machines
          env: "CYPRESS_RECORD_KEY=dc31c3bc-2297-4d6d-b63c-948af418373b"
